# Generated by Django 4.0.6 on 2024-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporte', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
